export const responses = [
    "Find another route", 
    "Cannot Predict Now", 
    "As I see it, yes", 
    "Outlook not so good", 
    "It is certain", 
    "Most Likely", 
    "Yes", 
    "Yes", 
    "Most Likely", 
    "Outlook Good", 
    "Don't count on it", 
    "My sources say no", 
    "Reply hazy, try again", 
    "Outlook not so so good", 
    "Without a doubt", 
    "Better not tell you now", 
    "It is decidedly so", 
    "Yes definitely", 
    "Signs point to yes", 
    "It is certain", 
    "Concentrate and ask again", 
    "You may rely on it", 
    "Very doubtful ", 
    "My reply is no", 
    "Ask again later", 
    "Don't count on it", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 

]


