export const responses = [
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Go Fuck Yourself", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 
    "Find another route", 

]


